global:
  checkNewVersion: false
  sendAnonymousUsage: false

entryPoints:
  web:
    address: ":80"
    http:
      aliasHeadersStrategy: delete
  websecure:
    address: ":443"
    http:
      aliasHeadersStrategy: delete

providers:
  file:
    filename: /etc/traefik/dynamic.toml

certificatesResolvers:
  letsencrypt:
    acme:
      email: wzc112358@qq.com
      storage: /etc/traefik/acme.json
      httpChallenge:
        entryPoint: web

log:
  level: INFO
